### ISSUE TITLE
Add option to generate plots in Makefile

### ISSUE THREAD

**Issue by spacey-sooty** [Saxomophone/springy#3]
This could be under make run or with a new task like make plots

**Comment by Saxomophone** [comment]
fixed
https://github.com/Saxomophone/springy/commit/42b78d854b4ecb973820879ebbbf349453066ffe

**Comment by Saxomophone** [comment]
fixed
https://github.com/Saxomophone/springy/commit/42b78d854b4ecb973820879ebbbf349453066ffe
